### ISSUE TITLE
Independent Assessment uploads not showing 028 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#696] opened 2020-07-23 16:07 UTC
**Describe the bug**
When you click on Independent Assessments for 00028 you cannot see which ones have been uploaded. 

**To Reproduce**
1. Go to admin
2. Click on 00028
3. Scroll down to Independent Assessments 

**This appears to be the same for EVERY exercise which has used the platform for IAs**

**Expected behavior**
Should see the list of assessors and pending assessments, completed one and an option to download them.

**Comment by Rebecca-mcknight1991** [comment] 2020-07-24 11:49
@warrensearle this is closed right?

**Comment by warrensearle** [comment] 2020-07-24 13:20
Ah yes, sorry, the work has been done under #697, which is a duplicate of this ticket. Will close.

**Closed** 2020-07-24 13:20 UTC
