### ISSUE TITLE
Withdrawn applications should be 1) marked as withdrawn and 2) appear in that list 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#965] opened 2020-10-21 09:29 UTC
**Describe the bug**
When candidates are withdrawn on admin they stay in Review or whichever stage they are in and do not show as withdrawn. 

**To Reproduce**
1. Go to any staging exercise with candidates
2. Click on review
3. Click tick box on a candidate, set status, withdrawn

**Expected behavior**
1. Stay in the stage they are in but status says 'Withdrew application'
2. They also appear in the 'Withdrawn' section under applications

**Screenshots**
![Screenshot 2020-10-21 at 10.27.17.png](https://images.zenhubusercontent.com/5e4bbb99c920b007684ed9ba/4eb087b3-6656-4055-8901-6223ea48bf76)

**Additional context**
Need to gather this info for diversity - how many withdrawals at each stage but also not mix up with applications. 

- [ ] Withdrawals appear in 'Withdrawn' under Applications

- [ ] Status changes to 'Withdrew application' in whatever stage under Stages they withdrew in.

**Comment by warrensearle** [comment] 2020-10-21 09:55
This is a duplicate of admin#962 which is already in progress

**Closed** 2020-10-21 10:16 UTC
Labels: bug
