### ISSUE TITLE
Report improvements

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1081] opened 2020-11-24 11:46 UTC
The following reports are currently generated client-side from the `applications` collection. As such they are slow, or worse, with larger data sets (anything over a few hundred applications).

We should either make use of the more lightweight `applicationRecords` collection OR we should generate the report server-side as we do for Diversity and Qualifying Test Reports.

- [ ] Reports. Reasonable Adjustments
- [ ] Reports. Agency
- [ ] Reports. Handover

**Comment by KateMJAC** [comment] 2021-02-26 17:54
Assigned to Halcyon in March's WO.

**Comment by warrensearle** [comment] 2021-03-05 14:42
@JeremykJAC this task has some overlap with #1100. I'd suggest looking at the Diversity Report and the Exercises Export for possible ways to prepare the data server-side

**Comment by HalcyonJAC** [comment] 2021-03-12 16:22
Hi

As @warrensearle mentions above, the Handover and Reasonable Adjustments reports were covered in #1100, so I that just leaves the Agency report now.

Quick note though: The Agency report would show on-screen but the Export Button didn't actually do anything, it just stayed disabled and there was no code in place to construct the XLS data or download a file. It looks like the implementation for that hadn't been done yet that's all.

So... I have done the following:

   - Digital Platform - added a generateAgencyReport endpoint, which generates and stores the report in the database (under exercises.reports.agency)   
   - Admin - Implemented the Export Data button.
   - Admin - Moved the Export Data button to be above the datatable, to match the design of other pages (i.e. Report - Reasonable Adjustments)
   - Admin - Added a Refresh button, also to match the design of the other pages.
   
If any of the above needs changing let me know! :)

**Comment by HalcyonJAC** [comment] 2021-03-12 17:32
Hi

One more thing...

I have got the the Auth / Login endpoint working in Postman now, so there will be no need to comment out the auth code temporarily anymore (which is what was doing in the screen-share the other day).

I will post a quick How To guide on the Slack channel.

Darrel

**Comment by KateMJAC** [comment] 2021-03-24 14:12
@JeremykJAC @HalcyonJAC We are yet to implement the export for the agency report as the plan was to export this data directly to particular angencies such as the Criminal Records Office, HMRC etc etc. That's a bigger piece of work that is in the roadmap for a later date. 

As there is no code to enable any action here, am I right in thinking that testing only involves confirming that I can see the 'Export Data' button above the data table and see the newly added refresh button? I am able to see all of that. 

Based on the fact that these buttons currently have no functionality, would it be possible to hide them on the UI for now? As this may cause confussion amongst users. When we complete the final stages of the work we can make them visible again.

**Comment by HalcyonJAC** [comment] 2021-03-25 12:12
@KateMJAC 

I can confirm that this is working on 'develop' just fine. Here is a link to it, if it helps: 
https://admin-develop.judicialappointments.digital/exercises/wdpALbyICL7ZxxN5AQt8/reports/agency#sra

I discussed this with Warren and he suspects that the problem is that the report depends on whether Character Checks part of the exercise has been completed or not and perhaps that part of the system isn't being used yet. i.e. the Agency report will be blank if not.

**Comment by KateMJAC** [comment] 2021-04-11 13:54
Thank you @HalcyonJAC I tested it on Develop and all works well.

**Closed** 2021-04-15 08:19 UTC
Labels: admin: 0.60.0, bug
